//? Dados usados no projeto

const bookNames = [
    'Cálculo Avançado',
    'Álgebra Linear',
    'Introdução à Física',
    'Química Orgânica',
    'Estatística Aplicada',
    'Geometria Analítica',
    'Mecânica dos Fluidos',
    'Eletrônica Digital',
    'Programação em Python',
    'Teoria dos Grafos',
    'Introdução à Sociologia',
    'Filosofia Política',
    'História da Arte',
    'Antropologia Cultural',
    'Psicologia do Desenvolvimento',
    'Literatura Brasileira',
    'Economia Internacional',
    'Geografia Urbana',
    'Direito Constitucional',
    'Ciência Política',
    'Anatomia Humana',
    'Fisiologia Médica',
    'Bioquímica Clínica',
    'Farmacologia Básica',
    'Microbiologia e Imunologia',
    'Patologia Geral',
    'Genética Molecular',
    'Bioestatística',
    'Epidemiologia',
    'Bioética',
];

const namesPublishingCompany = [
    'Abril',
    'Globo',
    'Record',
    'Companhia das Letras',
    'Intrínseca',
    'Rocco',
    'Sextante',
    'Nova Fronteira',
    'Ática',
    'Saraiva',
];
const firstNames = [
    'Alice',
    'Miguel',
    'Sophia',
    'Arthur',
    'Manuela',
    'Bernardo',
    'Laura',
    'Heitor',
    'Valentina',
    'Davi',
    'Helena',
    'Lorenzo',
    'Isabella',
    'Théo',
    'Júlia',
    'Pedro',
    'Heloísa',
    'Gabriel',
    'Luiza',
    'Benjamin',
    'Lorena',
    'Matheus',
    'Lívia',
    'Lucas',
    'Giovanna',
    'Nicolas',
    'Maria',
    'Guilherme',
    'Beatriz',
    'Rafael',
    'Camila',
];

const lastNames = [
    'Silva',
    'Santos',
    'Oliveira',
    'Souza',
    'Pereira',
    'Rodrigues',
    'Almeida',
    'Lima',
    'Ferreira',
    'Costa',
    'Gomes',
    'Martins',
    'Rocha',
    'Ribeiro',
    'Alves',
    'Monteiro',
    'Melo',
    'Carvalho',
    'Freitas',
    'Barros',
    'Pinto',
    'Moura',
    'Cavalcanti',
    'Dias',
    'Castro',
    'Cardoso',
    'Nascimento',
    'Fernandes',
    'Araújo',
    'Cunha',
];

const nationality = [
    'Brasil',
    'Estados Unidos',
    'Inglaterra',
    'Alemanha',
    'França',
    'Itália',
    'Espanha',
    'Japão',
    'China',
    'Rússia',
];

export { namesPublishingCompany, firstNames, lastNames, nationality, bookNames };
